package collatz;

import java.util.ArrayList;


public class Main {
	
	public static void main(String[] args) {
		
		Collatz col = new Collatz (5000000);
		
		long start = System.currentTimeMillis();
		col.run();
		long end = System.currentTimeMillis();
		long time = end-start;		

		System.out.println("TESTING ALL NUMBERS UNDER (" + col.getThreshold() + ")...");
		System.out.println("- Longest chain was generated by " + col.getStartingNumber());
		System.out.println("- Chain length: " + col.getLength());
		System.out.println("- Execution time: " + time + " millisec. (about " + time/1000 +" sec)");

	}
	
}
