package main;
public class main {
	
	public static void main(String[] args) {
		
		int num = 5000000;
		
		long start = System.currentTimeMillis();
		SalehObj A = new SalehObj (num);
		//LatifObject A = new LatifObject(num)
		//TianObj A = new TianObj(num);
		long end = System.currentTimeMillis();
		long time = (end-start)/1000;		

		System.out.println("TESTING ALL NUMBERS UNDER (" + num + ")...");
		System.out.println("- Longest chain was generated by " + A.getStartingNumber());
		System.out.println("- Chain length: " + A.getLength());
		System.out.println("- Execution time: " + time + " sec\n");

	}
	
}
