import java.util.*;

public class main {
	
	public static void main(String[] args) {
		
		int num = 5000000;
		
		double start = System.currentTimeMillis();
		SalehObj A = new SalehObj (num);
		//LatifObject A = new LatifObject(num)
		//TianObj A = new TianObj(num);
		double end = System.currentTimeMillis();
		double time = (end-start)/1000;		
		
		System.out.println("TESTING ALL NUMBERS UNDER (" + num + ")...");
		System.out.println("- Longest chain was generated by " + A.getThreshold());
		System.out.println("- Chain length: " + A.getLength());
		System.out.println("- Running time: " + time + " seconds");
		
	}
	
}
